version: 0.2

phases:
  install:
    commands:
      - node --version
      - npm install -g npm@8
      - npm --version
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npx ts-node packages/cicd/buildChangedPackages
  post_build:
    commands:
      - echo Build completed on `date`
